std = "max"

files["spec"] = {
    std = "+busted"
}

exclude_files = {
    "libs/*",  -- Pretty sure we do not want to lint Ace and other libraries provided by others
}

globals = {
    "_",
    "_G",
    "C_ChallengeMode",
    "C_Map",
    "C_MythicPlus",
    "C_Timer",
    "DungeonTools",
    "DungeonToolsDB",
    "DungeonToolsEnemyMixin",
    "AddOnSkins",
    "BackdropTemplateMixin",
    "ChatFrame_AddMessageEventFilter",
    "ColorPickerFrame",
    "CombatLogGetCurrentEventInfo",
    "CreateFont",
    "CreateFrame",
    "CreateFramePoolCollection",
    "CreateTextureMarkup",
    "CreateTexturePool",
    "DrawLine",
    "ElvUI",
    "errorhandler",
    "GameTooltip",
    "GameTooltip_SetTitle",
    "GetAddOnMetadata",
    "GetCursorPosition",
    "GetItemQualityColor",
    "GetLocale",
    "GetScreenHeight",
    "GetScreenWidth",
    "GetSpellLink",
    "GetSpellInfo",
    "GetTime",
    "GetWorldElapsedTime",
    "HelpPlate_Hide",
    "HelpPlate_IsShowing",
    "HelpPlate_Show",
    "hooksecurefunc",
    "InterfaceOptionsFrame_OpenToCategory",
    "IsAddOnLoaded",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsInGroup",
    "IsShiftKeyDown",
    "LibStub",
    "LoadAddOn",
    "MDTScrollFrame",
    "MDTMapPanelFrame",
    "MDTToolbarFrame",
    "Mixin",
    "MouseIsOver",
    "QuestPOI_CalculateNumericTexCoords",
    "QUEST_POI_COLOR_BLACK",
    "ReloadUI",
    "SendChatMessage",
    "SetPortraitToTexture",
    "SetPortraitTextureFromCreatureDisplayID",
    "strsplit",
    "table.wipe",
    "UIFrameFadeOut",
    "UIParent",
    "UISpecialFrames",
    "UnitCreatureType",
    "UnitFactionGroup",
    "UnitFullName",
    "UnitGUID",
    "UnitHealthMax",
    "UnitInRaid",
    "UnitLevel",
    "UnitName",
    "WrapTextInColorCode",
    "EJ_GetCreatureInfo",
    "EJ_GetInstanceForMap",
    "L_EasyMenu",
    "L_CloseDropDownMenus",
    "L_Create_UIDropDownMenu",
    "DEFAULT_CHAT_FRAME",
    "debugprofilestop",
    "ViragDevTool_AddData",
    "SLASH_DUNGEONTOOLS1",
    "SLASH_DUNGEONTOOLS2",
    "SLASH_DUNGEONTOOLS3",
    "BINDING_NAME_DungeonToolsToggle",
    "BINDING_NAME_DungeonToolsNPC",
    "BINDING_NAME_DungeonToolsWaypoint",
    "SlashCmdList",
}

ignore = {
    "212", -- ignore unused function arguments (reasoning: module:function passes self but if self is never used this warns)
    "432", -- ignore shadowing upvalue argument.  Most common example shadows self: function foo:froo() {  code; local bar = {}; function bar:baz(thing) { self.stuff = thing}}
}

max_line_length = false
